<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>
    
    <PropertyGroup>
        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
        <CompilerGeneratedFilesOutputPath>$(BaseIntermediateOutputPath)GeneratedFiles</CompilerGeneratedFilesOutputPath>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector" Version="6.0.4"/>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.1" />
        <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.1" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.0"/>
        <PackageReference Include="NUnit" Version="4.4.0" />
        <PackageReference Include="NUnit.Analyzers" Version="4.7.0"/>
        <PackageReference Include="NUnit3TestAdapter" Version="5.0.0"/>
        <PackageReference Include="SimpleBitware.AspectNet" Version="0.0.0-alpha.0.4" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="NUnit.Framework"/>
    </ItemGroup>

<!--    <ItemGroup>-->
<!--      <ProjectReference Include="..\..\src\SimpleBitware.AspectNet.Attributes\SimpleBitware.AspectNet.Attributes.csproj" />-->
<!--      <ProjectReference Include="..\..\src\SimpleBitware.AspectNet.Runtime\SimpleBitware.AspectNet.Runtime.csproj" />-->
<!--      <ProjectReference Include="..\..\src\SimpleBitware.AspectNet.Generator\SimpleBitware.AspectNet.Generator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />-->
<!--    </ItemGroup>-->

</Project>
