<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <LangVersion>latest</LangVersion>
    </PropertyGroup>

    <PropertyGroup>
        <PackageId>SimpleBitware.Aop</PackageId>
        <Version>1.0.0</Version>
        <Authors>Lucian Bornaz</Authors>
        <Company>Simple Bitware</Company>
        <Description>Aspect-Oriented Programming for .NET with Roslyn Source Generators.</Description>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageProjectUrl>https://github.com/SimpleBitware/Aop</PackageProjectUrl>
        <RepositoryUrl>https://github.com/SimpleBitware/Aop</RepositoryUrl>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <IncludeBuildOutput>false</IncludeBuildOutput>
        <BuildOutputTargetFolder />
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <IsPackable>true</IsPackable>
        <MinVerTagPrefix>v</MinVerTagPrefix>
    </PropertyGroup>

    <ItemGroup>
        <None Include="..\..\README.md" Pack="true" PackagePath="README.md" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="MinVer" Version="6.0.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>
    
    <ItemGroup>
        <!-- Attributes library -->
        <ProjectReference Include="..\SimpleBitware.Aop.Attributes\SimpleBitware.Aop.Attributes.csproj" PrivateAssets="none" ReferenceOutputAssembly="true" />
        
        <!-- Runtime library -->
        <ProjectReference Include="..\SimpleBitware.Aop.Runtime\SimpleBitware.Aop.Runtime.csproj" PrivateAssets="none" ReferenceOutputAssembly="true" />
        
        <!-- Analyzer (source generator) -->
        <ProjectReference Include="..\SimpleBitware.Aop.Generator\SimpleBitware.Aop.Generator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" PrivateAssets="all" />
        
        <!-- Ship design-time stubs to consumers -->
        <None Include="buildTransitive\*.cs" Pack="true" PackagePath="buildTransitive\" />
    </ItemGroup>

    <ItemGroup>
        <!-- Pack Attributes DLL -->
        <None Include="bin\$(Configuration)\netstandard2.0\SimpleBitware.Aop.Attributes.dll" Pack="true" PackagePath="lib/netstandard2.0/" />

        <!-- Pack Runtime DLL -->
        <None Include="bin\$(Configuration)\netstandard2.0\SimpleBitware.Aop.Runtime.dll" Pack="true" PackagePath="lib/netstandard2.0/" />
    </ItemGroup>

</Project>