<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>

        <!-- Required for MSBuild tasks -->
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\SimpleBitware.AspectNet\SimpleBitware.AspectNet.csproj"/>
    </ItemGroup>

    <UsingTask
            TaskName="AspectNetWeaverTask"
            AssemblyFile="$(ProjectDir)bin\$(Configuration)\$(TargetFramework)\SimpleBitware.AspectNet.dll"/>

    <Target Name="RunAspectNetWeaver" AfterTargets="Build">
        <AspectNetWeaverTask
                AssemblyPath="$(TargetPath)"
                References="@(ReferencePath)"
                ShowWeavingLogs="True"
                GenerateDebugFiles="True"/>
    </Target>

</Project>
