<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <LangVersion>latest</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="PolySharp" Version="1.16.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <ProjectReference Include="..\..\src\SimpleBitware.AspectNet.Abstractions\SimpleBitware.AspectNet.Abstractions.csproj"/>
        <ProjectReference Include="..\..\src\SimpleBitware.AspectNet\SimpleBitware.AspectNet.csproj"/>
    </ItemGroup>

    <UsingTask
            TaskName="AspectNetWeaverTask"
            AssemblyFile="$(ProjectDir)bin\$(Configuration)\$(TargetFramework)\SimpleBitware.AspectNet.dll"/>

    <Target Name="RunAspectNetWeaver" AfterTargets="Build">
        <AspectNetWeaverTask
                AssemblyPath="$(TargetPath)"
                References="@(ReferencePath)"
                LogLevel="Debug"/>
    </Target>

</Project>
