<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
    </PropertyGroup>

    <PropertyGroup>
        <PackageId>SimpleBitware.AspectNet</PackageId>
        <Description>AspectNet enables aspect oriented programming</Description>
        <Authors>Lucian Bornaz</Authors>
        <Company>Simple Bitware</Company>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageProjectUrl>https://github.com/SimpleBitware/AspectNet/tree/main/src/SimpleBitware.AspectNet</PackageProjectUrl>
        <RepositoryUrl>https://github.com/SimpleBitware/AspectNet</RepositoryUrl>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageIcon>logo.png</PackageIcon>

        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <IncludeBuildOutput>false</IncludeBuildOutput>
        <NoPackageAnalysis>true</NoPackageAnalysis>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
        <MinVerTagPrefix>v</MinVerTagPrefix>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\SimpleBitware.AspectNet.Abstractions\SimpleBitware.AspectNet.Abstractions.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Ardalis.GuardClauses" Version="5.0.0"/>
        <PackageReference Include="Microsoft.Build.Utilities.Core" Version="17.0.0"/>
        <PackageReference Include="Mono.Cecil" Version="0.11.6" PrivateAssets="all"/>
        <PackageReference Include="morelinq" Version="4.4.0"/>
        <PackageReference Include="MinVer" Version="6.0.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <None Include="..\..\README.md"
              Pack="true"
              PackagePath=""
              Visible="false"/>
        <None Include="..\..\logo.png"
              Pack="true"
              PackagePath=""
              Visible="false"/>
        <None Include="$(OutputPath)\*.dll"
              Exclude="$(OutputPath)\System.*;
                       $(OutputPath)\Microsoft.Build.*;
                       $(OutputPath)\Microsoft.Extensions.*;
                       $(OutputPath)\Microsoft.Bcl.*;
                       $(OutputPath)\Microsoft.NET.*;
                       $(OutputPath)\netstandard.dll"
              Pack="true"
              PackagePath="tasks/$(TargetFramework)"
              Visible="false"/>
        <None Include="Package\build\SimpleBitware.AspectNet.targets"
              Pack="true"
              PackagePath="build"/>
        <None Include="Package\build\SimpleBitware.AspectNet.props"
              Pack="true"
              PackagePath="build"/>
    </ItemGroup>

</Project>
