<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
    </PropertyGroup>

    <PropertyGroup>
        <PackageId>SimpleBitware.AspectNet</PackageId>
        <Description>AspectNet enables aspect oriented programming</Description>
        <Authors>Lucian Bornaz</Authors>
        <Company>Simple Bitware</Company>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageProjectUrl>https://github.com/SimpleBitware/AspectNet/tree/main/src/SimpleBitware.AspectNet</PackageProjectUrl>
        <RepositoryUrl>https://github.com/SimpleBitware/AspectNet</RepositoryUrl>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageIcon>logo.png</PackageIcon>

        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <IncludeBuildOutput>false</IncludeBuildOutput>
        <NoPackageAnalysis>true</NoPackageAnalysis>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
        <DevelopmentDependency>true</DevelopmentDependency>
        <MinVerTagPrefix>v</MinVerTagPrefix>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\SimpleBitware.AspectNet.Cecil\SimpleBitware.AspectNet.Cecil.csproj" PrivateAssets="All"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Build.Utilities.Core" Version="18.6.3"/>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.9" />
        <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.8"/>
        <PackageReference Include="MinVer" Version="7.0.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <None Include="..\..\README.md"
              Pack="true"
              PackagePath=""
              Visible="false"/>
        <None Include="..\..\resources\logo.png"
              Pack="true"
              PackagePath=""
              Visible="false"/>
        <None Include="Package\build\SimpleBitware.AspectNet.targets"
              Pack="true"
              PackagePath="build"/>
        <None Include="Package\build\SimpleBitware.AspectNet.props"
              Pack="true"
              PackagePath="build"/>
    </ItemGroup>

    <PropertyGroup>
        <TargetsForTfmSpecificContentInPackage>$(TargetsForTfmSpecificContentInPackage);AddTaskAssembliesToPack</TargetsForTfmSpecificContentInPackage>
    </PropertyGroup>

    <Target Name="AddTaskAssembliesToPack">
        <ItemGroup>
            <TfmSpecificPackageFile Include="$(TargetDir)*.dll">
                <PackagePath>tasks/$(TargetFramework)/</PackagePath>
            </TfmSpecificPackageFile>
        </ItemGroup>
    </Target>

</Project>
