<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    
    <PropertyGroup>
        <IsRoslynAnalyzer>true</IsRoslynAnalyzer>
<!--        <IsRoslynComponent>false</IsRoslynComponent>-->
        <EnforceExtendedAnalyzerRules>false</EnforceExtendedAnalyzerRules>
        
        <!-- REQUIRED for source generators -->
        <OutputType>Library</OutputType>

        <!-- Generators should not be packable -->
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <PropertyGroup>
        <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
    </PropertyGroup>
    
    <ItemGroup>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.10.0" PrivateAssets="all" />
    </ItemGroup>
    
    <ItemGroup>
      <ProjectReference Include="..\SimpleBitware.AspectNet.Runtime\SimpleBitware.AspectNet.Runtime.csproj" />
    </ItemGroup>

</Project>
