<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
    </PropertyGroup>

    <PropertyGroup>
        <PackageId>SimpleBitware.AspectNet.Cecil</PackageId>
        <Authors>Lucian Bornaz</Authors>
        <Company>Simple Bitware</Company>
        <Description>Extensions methods for Cecil</Description>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageProjectUrl>https://github.com/SimpleBitware/AspectNet/tree/main/src/SimpleBitware.Cecil</PackageProjectUrl>
        <RepositoryUrl>https://github.com/SimpleBitware/AspectNet</RepositoryUrl>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageIcon>logo.png</PackageIcon>

        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <IncludeBuildOutput>true</IncludeBuildOutput>
        <MinVerTagPrefix>v</MinVerTagPrefix>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Mono.Cecil" Version="0.11.6"/>
        <PackageReference Include="morelinq" Version="4.4.0"/>
        <PackageReference Include="MinVer" Version="7.0.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="System.Collections.Immutable" Version="10.0.6" />
    </ItemGroup>

    <ItemGroup>
        <None Include="..\..\README.md"
              Pack="true"
              PackagePath=""
              Visible="false"/>
        <None Include="..\..\resources\logo.png"
              Pack="true"
              PackagePath=""
              Visible="false"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\SimpleBitware.AspectNet.Abstractions\SimpleBitware.AspectNet.Abstractions.csproj" />
    </ItemGroup>

</Project>
