<Project Sdk="Microsoft.NET.Sdk">
    
    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
    </PropertyGroup>
    
    <ItemGroup>
        <Analyzer Include="..\..\src\SimpleBitware.AspectNet.Analyzers\bin\Debug\netstandard2.0\SimpleBitware.AspectNet.Analyzers.dll"/>
        <Analyzer Include="..\..\src\SimpleBitware.AspectNet.CodeFixes\bin\Debug\netstandard2.0\SimpleBitware.AspectNet.CodeFixes.dll"/>
    </ItemGroup>
    
    <ItemGroup>
      <PackageReference Include="SimpleBitware.AspectNet" Version="1.0.0" />
    </ItemGroup>
    
</Project>
