<Project Sdk="Microsoft.NET.Sdk">
    
    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ReportAnalyzer>true</ReportAnalyzer>
        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
        <LangVersion>latest</LangVersion>
    </PropertyGroup>
    
    <ItemGroup>
      <PackageReference Include="SimpleBitware.AspectNet.Abstractions" Version="0.0.0-alpha.0.23" />
    </ItemGroup>
    
</Project>
